### ISSUE TITLE
Errors in Advanced MIS documentation

### ISSUE THREAD

**Issue by drenfree** [talis/advanced-mis#37]
Queensland have noted some issues that need correcting:

Also, we note two errors in the documentation at: https://talis.github.io/advanced-mis/topics/users.html

1. the 'name' field has the Description 'Canonical URL of the reading list'
2. There is an extra field in the data, not mentioned in the documentation, between "aspire_role" and "year_last_logged_in" that appears to be last login date.

https://talisaspire.zendesk.com/agent/tickets/32872

**Comment by timhodson** [comment]
Will be fixed when Elevate tables documentation goes live
